default_email_domain: foo.bar # users email domain
ldap:
  base_dn: # Base domain of the search of ldap
    ou:
      - US
    dc:
      - dhna
      - corp
  user_context: # context information used as part of the username in the credentials
    OU:
      - example1
      - example2
    DC:
      - example3
      - example4
  connection_string: 'ldaps://foo.bar:8888' #connection string for your ldap server
  search_filter: 'cn=*'
  retrieve_attributes: #LDAP attributes that you want to retrieve.
  #while more can be expected these 3 entries are expected.
    - name
    - email
    - displayName
